url: 'https://jpbongiovanni.github.io/'
baseurl: 'PythonFunctionLibrary/'

title: Veera Adithya Dittakavi
author:
  name: Veera Adithya Dittkavi
  email: veera.adithya.d@gmail.com

logo: headshot.png

description: >
  Portfolio showcasing machine learning track in computer vision, natural language processing, and optimization, along with my research outputs.
theme: jekyll-theme-minimal
show_downloads: true

